language: python
python:
  - "2.7"
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt

addons:
  postgresql: "9.3"

services:
  - redis-server

before_script:
  - psql -c 'create database newslynx;' -U postgres

script:
    - make app_install