language: python
python:
  - "2.7"



# command to install dependencies
install:
    - 

sudo: yes

addons:
  postgresql: "9.3"

services:
  - redis-server

before_script:
  - psql -c 'create database newslynx;' -U postgres
  - sudo apt-get install -y libxml2-dev libxml2-dev libxml2-dev libxslt1-dev libffi-dev postgresql-plpython python-pip python-dev python-setuptools pandoc

script:
    - make app_install