# CUSTOM
export NEWSLYNX_DATABASE_URI="postgresql://newslynx:rds-m3rlynn3@newslynx-pro.cujss8z6ggv8.us-east-1.rds.amazonaws.com:5432/newslynx"
export NEWSLYNX_DATABASE_USER="newslynx"
export NEWSLYNX_DATABASE_PASSWORD="rds-m3rlynn3"
export NEWSLYNX_DATABASE_HOST="newslynx-pro.cujss8z6ggv8.us-east-1.rds.amazonaws.com"
export NEWSLYNX_DATABASE_PORT="5432"
export NEWSLYNX_DATABASE_NAME='newslynx'
export NEWSLYNX_API_SECRET_KEY='Burrito ramen burger'
export NEWSLYNX_APP_SECRET_KEY='Rattatouille omelet eclair'
export NEWSLYNX_ADMIN_PASSWORD='admin-m3rlynn3'
export NEWSLYNX_API_URL='http://towcenter.newslynx.org:5000'
export NEWSLYNX_APP_URL='http://towcenter.newslynx.org'

# DEFAULTS
export NEW_RELIC_CONFIG_FILE='/home/ubuntu/newslynx/conf/pro/newrelic.ini' 
export NEWSLYNX_TWITTER_API_KEY='451Wf48Bw0QzmBAh7xW8H1EHa'
export NEWSLYNX_TWITTER_API_SECRET='brV8iuI3MoIqdePTPZ398lOXNeO8PhatebVcanxUz1bJwgz7he'
export NEWSLYNX_TWITTER_OAUTH_TOKEN='2419585021-e4aRbhCsFHkt6mxl8WrOMyB1UQWAtmjBQFbQ01s'
export NEWSLYNX_TWITTER_OAUTH_SECRET='k0xCWxVre4HKLzlurnlgaIy6lqeKY9UmOMBp3bRf8nXao'
export NEWSLYNX_GOOGLE_ANALYTICS_CLIENT_ID='35445462100-fbqog7qiacu110sff2qs73pt6084d5ht.apps.googleusercontent.com'
export NEWSLYNX_GOOGLE_ANALYTICS_CLIENT_SECRET='69famMizG62nk4IpY8qYq-Ku'
export NEWSLYNX_FACEBOOK_APP_ID='566110656837853'
export NEWSLYNX_FACEBOOK_APP_SECRET='e446d8b5174ef530ec0c8147db9248db'
export NEWSLYNX_ELASTIC_SEARCH_URL='localhost:9200'
export NEWSLYNX_ELASTIC_SEARCH_INDEX='newslynx'
export NEWSLYNX_EMBEDLY_API_KEY='256fa72a820e47b993db3145fc51c94b'
export NEWSLYNX_EMAIL_USERNAME='merlynne@newslynx.org'
export NEWSLYNX_EMAIL_PASSWORD='m41l!-m3rlynn3'
export NEWSLYNX_EMAIL_SERVER='mail.gandi.net'
export NEWSLYNX_EMAIL_PORT=587
export NEWSLYNX_EMAIL_ERROR_RECIPIENTS='brianabelson@gmail.com, brian@newslynx.org'
export NEWSLYNX_CELERY_BROKER_URL='redis://localhost:6379'
export NEWSLYNX_CELERY_RESULT_BACKEND='redis://localhost:6379'
export NEWSLYNX_SSL_PORT=443
export NEWSLYNX_HTTP_PORT=3000
export NEWSLYNX_AWS_ACCESS_KEY_ID='AKIAJ37M3Q6HCYGJTK7A'
export NEWSLYNX_AWS_SECRET_ACCESS_KEY='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'
export ES_HEAP_SIZE=30g


# app configurations #
api_url: 
api_port: 

# dev configuration
debug_timing:

# security
secret_key: 
admin_user: 
admin_password:
admin_email:

# database config
sqlalchemy_database_uri: 
sqlalchemy_pool_size: 
sqlalchemy_pool_max_overflow:
sqlalchemy_pool_timeout: 
sqlalchemy_echo: 

# task queue
celery_broker_url: 
celery_result_backend: 

# new relic 
new_relic_config_file: 

# twitter (for event creation + metrics)
twitter_api_key: 
twitter_api_secret: 

# google analytics (for metrics)
google_analytics_client_id: 
google_analytics_client_secret: 

# facebook (for event creation)
facebook_app_id: 
facebook_app_secret: 

# embedly (for content extraction)
embedly_api_key: 

# bitly (for url normalization + click stats)
bitly_api_key: 


# email #

mail_username: 
mail_password: 
mail_server: 
smtp_port: 
imap_port: 


