# api configurations #
api_url: http://localhost:5000
api_port: 5000
api_version: v1

# app configurations
newslynx_app_secret_key: chicken-burrito-grande

# security
secret_key: uqbar
super_user: Merlynne Jones
super_user_password: my-password
super_user_email: merlynne@newslynx.org
super_user_apikey: my-api-key