# app configurations #
api_url: http://localhost:5000
api_port: 5000

# dev configuration
debug_timing: true

# security
secret_key: super-secret-key
admin_user: Merlynne Jones
admin_password: super-secret-password
admin_email: merlynne@example.com
super_user_password: tk

# database config
sqlalchemy_database_uri: postgres://username:password@localhost:5432/newslynx 
sqlalchemy_pool_size: 1000
sqlalchemy_pool_max_overflow: 100
sqlalchemy_pool_timeout: 30
sqlalchemy_echo: false

# task queue
redis_url: redis://localhost:6379/0
scheduler_refresh_interval: 60

# url cache
url_cache_prefix: url-cache
url_cache_ttl: 259200 # 3 days

# browser
browser_user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10; rv:33.0) Gecko/20100101 Firefox/33.0
browser_timeout: 10
browser_max_retries: 5

# twitter (for event creation + metrics)
twitter_api_key: slkdfjaslkfjadlskfjalsfa
twitter_api_secret: slkdfjaslkfjadlskfjalsfa

# google analytics (for metrics)
google_analytics_client_id: slkdfjaslkfjadlskfjalsfa
google_analytics_client_secret: slkdfjaslkfjadlskfjalsfa

# facebook (for event creation)
facebook_app_id: 321431431242314213
facebook_app_secret: slkdfjaslkfjadlskfjalsfa

# embedly (for content extraction)
embedly_api_key: slkdfjaslkfjadlskfjalsfa

# bitly (for url normalization + click stats)
bitly_api_key: slkdfjaslkfjadlskfjalsfa


# email #

# for sending emails
mail_username: merlynne@example.com
mail_password: super-secret-password
mail_server: mail.example.com
smtp_port: 587
imap_port: 993


